log:
  level: debug
ssh:
  hostkeys:
    - ./ssh_host_rsa_key
backend: docker
auth:
  url: "https://auth-vdjr.onrender.com"
  pubkey: false
configserver:
  url: "https://auth-vdjr.onrender.com/config"
